package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// User is a row of the users table. The password hash lives here and nowhere
// else; it is never part of any response shape.
type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	FullName     string
	CreatedAt    time.Time
}

// UsersEmailConstraint is the unique index on users.email, named so a caller can
// tell an already-registered address from any other conflict.
const UsersEmailConstraint = "users_email_key"

// CreateUser inserts a user, returning ErrConflict if the e-mail is taken.
//
// The id is supplied rather than generated by the database because the seeder
// imports the dataset's own user ids, and a registration mints one in Go. One
// code path either way is simpler than two.
func (q *Queries) CreateUser(ctx context.Context, u User) (User, error) {
	const query = `
		INSERT INTO users (id, email, password_hash, full_name)
		VALUES ($1, $2, $3, $4)
		RETURNING created_at`

	err := q.q.QueryRow(ctx, query, u.ID, u.Email, u.PasswordHash, u.FullName).Scan(&u.CreatedAt)
	if err != nil {
		return User{}, wrap("store.CreateUser", err)
	}
	return u, nil
}

// UserByEmail looks a user up for login. Matching is case-insensitive because
// the column is CITEXT, so the comparison is the database's job rather than a
// normalisation step every caller has to remember.
func (q *Queries) UserByEmail(ctx context.Context, email string) (User, error) {
	const query = `
		SELECT id, email, password_hash, full_name, created_at
		FROM users WHERE email = $1`

	var u User
	err := q.q.QueryRow(ctx, query, email).
		Scan(&u.ID, &u.Email, &u.PasswordHash, &u.FullName, &u.CreatedAt)
	if err != nil {
		return User{}, wrap("store.UserByEmail", err)
	}
	return u, nil
}

// UserByID loads the authenticated user for /api/me.
func (q *Queries) UserByID(ctx context.Context, id uuid.UUID) (User, error) {
	const query = `
		SELECT id, email, password_hash, full_name, created_at
		FROM users WHERE id = $1`

	var u User
	err := q.q.QueryRow(ctx, query, id).
		Scan(&u.ID, &u.Email, &u.PasswordHash, &u.FullName, &u.CreatedAt)
	if err != nil {
		return User{}, wrap("store.UserByID", err)
	}
	return u, nil
}

// EmailExists reports whether an address is already registered.
//
// It exists for the registration form's inline validation, not for the
// registration itself: checking and then inserting is a race, so CreateUser's
// unique constraint stays the authority.
func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	const query = `SELECT EXISTS (SELECT 1 FROM users WHERE email = $1)`

	var exists bool
	if err := q.q.QueryRow(ctx, query, email).Scan(&exists); err != nil {
		return false, wrap("store.EmailExists", err)
	}
	return exists, nil
}
